image jin = "images/character/@2/white.png"
image mina = "images/character/@2/pink.png"
image nia = "images/character/@2/yellow.png"
image sein = "images/character/@2/black.png"
image kato = "images/character/@2/blue.png"
image rui = "images/character/@2/purple.png"
image ian = "images/character/@2/red.png"
image moro = "images/character/@2/green.png"
image jun = "images/character/@2/brown.png"

image bg letter = "images/background/bg letter.png"
image bg mansion entrance = "images/background/bg mansion entrance.png"
image bg dining room = "images/background/bg dining room.png"
image bg kitchen = "images/background/bg kitchen.png"
image bg corridor = "images/background/bg corridor.png"
image bg corridor footprint = "images/background/bg corridor footprint.png"
image bg corridor wine = "images/background/bg corridor wine.png"
image bg courtyard = "images/background/bg courtyard.png"
image bg lobby = "images/background/bg lobby.png"
image bg west living room = "images/background/bg west living room.png"
image bg power = "images/background/bg power.png"
image bg reading room = "images/background/bg reading room.png"
image bg study fire = "images/background/bg study fire.png"
image bg study extinguishing = "images/background/bg study extinguishing.png"
image bg study burnt = "images/background/bg study burnt.png"
image bg main = "images/background/bg main.png"
image bg over = "images/background/bg over.png"

image book = "images/ui/screen/book.png"
image map = "images/ui/screen/map.png"

image ic_jin = "images/ui/icon/white.png"
image ic_mina = "images/ui/icon/pink.png"
image ic_nia = "images/ui/icon/yellow.png"
image ic_sein = "images/ui/icon/black.png"
image ic_kato = "images/ui/icon/blue.png"
image ic_rui = "images/ui/icon/purple.png"
image ic_ian = "images/ui/icon/red.png"
image ic_moro = "images/ui/icon/green.png"
image ic_jun = "images/ui/icon/brown.png"

image note = "images/ui/icon/note.png"
image spill = "images/ui/icon/spill.png"
image igature = "images/ui/icon/igature.png"
image ashes = "images/ui/icon/ashes.png"
image stab = "images/ui/icon/stab.png"
image cctv = "images/ui/icon/cctv.png"
image screen = "images/ui/icon/cctv_screen.png"
image footprint = "images/ui/icon/footprint.png"

image ev_igature = "images/ui/evidence/ev_igature.png"
image ev_ashes = "images/ui/evidence/ev_ashes.png"
image ev_stab = "images/ui/evidence/ev_stab.png"
image ev_cctv = "images/ui/evidence/ev_cctv.png"
image ev_screen = "images/ui/evidence/ev_cctv_screen.png"
image ev_footprint = "images/ui/evidence/ev_footprint.png"